colorscheme slate
set autoindent
set backspace=indent,eol,start
set hlsearch
set incsearch
set linebreak
set mouse=a
set number
set ruler
set shiftwidth=4
set showmatch
set smartcase
set smartindent
set softtabstop=4
set textwidth=80
set undolevels=10000
set visualbell
